### ISSUE TITLE
Is the package definition necessary for the SDK missing?

### ISSUE THREAD

**Issue by y-kuzunoha** [NANJ-COIN/android-sdk#4]
Hi, NANJCOIN development team

I am trying to implement the wallet function using the Android version of NANJCOIN SDK.
However, when writing and running the first wallet creation code I got the following error.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.goldship.dev.nanjwallettrial, PID: 6567
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jetbrains/anko/AsyncKt;
        at com.nanjcoin.sdk.nanj.NANJWalletManager.createWallet(NANJWalletManager.kt:299)
        at com.goldship.dev.nanjwallettrial.HomeActivity.createWallet(HomeActivity.kt:31)
        at com.goldship.dev.nanjwallettrial.HomeActivity.access$createWallet(HomeActivity.kt:16)
        at com.goldship.dev.nanjwallettrial.HomeActivity$onCreate$1.onClick(HomeActivity.kt:26)
        at android.view.View.performClick(View.java:6256)
        at android.view.View$PerformClick.run(View.java:24701)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```
I was able to solve this error by adding the following code to the dependencies of build.gradle.

> implementation "org.jetbrains.anko: anko: 0.10.6"

I think the org.jetbrains.anko package is a necessary package in the NANJCOIN SDK, but maybe an error occurs because dependencies are not properly defined.

I would like you to check and fix it.
best regards.

**Comment by tuanes** [comment]
Thanks for posting this issue. 
Our team will check!

**Comment by y-kuzunoha** [comment]
@tuanes Thank you for confirming.
I will look forward to the update.

**Comment by y-kuzunoha** [comment]
Hi, NANJ Blockchain Team.

Thanks for updating the SDK.
I will to confirm it in the few days.

[Wallet creation fails # 5](https://github.com/NANJ-COIN/android-sdk/issues/5)
will check this together as well.

**Comment by y-kuzunoha** [comment]
Hi, NANJ Blockchain Team.

Has SDK ver 1.1.0 been released?
I did not find the release tag of ver 1.1.0

> This release will be more detail of "How to use NANJ SDK?".

Where is "How to use NANJ SDK?"

I tried using SDK ver 1.1 of the rerease branch (release / 1.1.0).
Unfortunately, the issue has not been resolved.

I would your confirmation please.

**Comment by tuanes** [comment]
Hi @y-kuzunoha, 
Thanks for your great efforts on following up. 
We're doing some important testings and verifications for NANJ Android SDK. 

For using branch release 1.1.0, 
Please refer to the example _(gradle file, we specified the project dependencies)_, if you're having a problem with your API Key and Secret Key, please email to us support@nanjcoin.com for further assistance. If you need NANJCOINTest for the test environment, please share us your wallet address, we can send NAJNCOINTest for your testing. 

In order to use your API Key and Secret Key properly, your application _(in our developer page)_ have to be approved by our admin. 

Cheers,

Thanks for using our SDK!
**NANJ Blockchain Team**

**Comment by y-kuzunoha** [comment]
Thanks, @tuanes.
I implemented it with reference to "android-sdk / NANJ / build.gradle".
It confirmed that the build succeeded.

I appreciate your support.
