### ISSUE TITLE
Wallet creation fails

### ISSUE THREAD

**Issue by y-kuzunoha** [NANJ-COIN/android-sdk#5]
Hi, NANJCOIN development team.

I am trying to implement the NANJ Wallet creation.
But, it has failed due to an error.

Am I doing the wrong implementation?
Or is there a missing implementation?

I coded the Application class as below.
```
    override fun onCreate() {
        super.onCreate()
        NANJWalletManager.Builder()
                .setContext(applicationContext)
                .setDevelopmentMode(true)
                .setNANJAppId(APP_ID)
                .setNANJSecret(SECRET_KEY)
                .build()
    }
```
For APP_ID and SECRET_KEY we defined the values issued at https://developers.nanjcoin.com.

Next, we defined the below method for MainActivity and called it.
```
private fun createWallet() {

        nanjWalletManager?.createWallet(
                object : NANJCreateWalletListener {
                    override fun onCreateProcess(@Nullable backup: String?) {
                        Toast.makeText(this@MainActivity, "Create wallet success.", Toast.LENGTH_LONG).show()
                        AppLog.d("MainActivity", "backup:$backup")
                        var address = nanjWalletManager?.wallet?.nanjAddress
                        AppLog.d("MainActivity", "address:$address")
                    }

                    override fun onCreateWalletFailure() {
                        runOnUiThread {
                            Toast.makeText(this@MainActivity, "Create wallet failure.", Toast.LENGTH_LONG).show()
                        }
                    }
                }
        )

    }
```

The result was the following error.
```
java.lang.RuntimeException: Unable to execute Ethereum request
     at org.web3j.ens.EnsResolver.resolve(EnsResolver.java:77)
     at org.web3j.tx.Contract.<init>(Contract.java:55)
     at org.web3j.tx.Contract.<init>(Contract.java:65)
     at com.nanjcoin.sdk.smartcontract.NANJSmartContract.<init>(NANJSmartContract.kt:42)
     at com.nanjcoin.sdk.smartcontract.NANJSmartContract$Companion.load(NANJSmartContract.kt:815)
     at com.nanjcoin.sdk.smartcontract.NANJSmartContract$Companion.load$default(NANJSmartContract.kt:814)
     at com.nanjcoin.sdk.nanj.NANJWallet.initNANJSmartContract(NANJWallet.kt:74)
     at com.nanjcoin.sdk.nanj.NANJWallet.init(NANJWallet.kt:68)
     at com.nanjcoin.sdk.nanj.NANJWalletManager$createWallet$2.invoke(NANJWalletManager.kt:314)
     at com.nanjcoin.sdk.nanj.NANJWalletManager$createWallet$2.invoke(NANJWalletManager.kt:28)
     at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:143)
     at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
     at org.jetbrains.anko.AsyncKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
     at java.lang.Thread.run(Thread.java:764)
 Caused by: org.web3j.tx.exceptions.ContractCallException: Empty value (0x) returned from contract
     at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:194)
     at org.web3j.tx.Contract$2.call(Contract.java:257)
     at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:31)
     at org.web3j.ens.EnsResolver.resolve(EnsResolver.java:75)
 7150-7211/com.goldship.dev.nanjwallettrial W/System.err: 	... 17 more
```

**Comment by y-kuzunoha** [comment]
Thanks, I will look at the sample carefully and try it.
I appreciate your support.
